#!/usr/bin/env python3
"""Generate Sources/MinutesCore/Redaction/FirstNames.swift, the first-name lexicon used to redact
names Apple's named-entity recognizer misses.

Maintainer tool; its output is committed. Source: US Social Security Administration baby-name
counts 1880–2017 (public domain), as packaged in the CC0-licensed `babynames` R package
(https://github.com/hadley/babynames). SSA's own download blocks scripted access.

Keeps every name given to at least MIN_BIRTHS US babies since 1930 (people alive today), which
covers many names from outside the US, e.g. Priya, Arjun, Wei, Olufemi, Kwame.

Usage:
    python3 -m venv /tmp/names-venv && /tmp/names-venv/bin/pip install rdata
    /tmp/names-venv/bin/python scripts/generate_first_names.py
"""

import tempfile
import urllib.request
from pathlib import Path

import rdata

SOURCE = "https://github.com/hadley/babynames/raw/master/data/babynames.rda"
MIN_BIRTHS = 300
SINCE_YEAR = 1930
OUTPUT = Path(__file__).resolve().parent.parent / "Sources/MinutesCore/Redaction/FirstNames.swift"

# Names that are far more often something else in meeting speech: calendar words, titles, and
# well-known places (names that are mostly personal names, like Madison or Jordan, stay in).
EXCLUDED = set(
    """
    january february march april may june july august september october november december
    monday tuesday wednesday thursday friday saturday sunday
    christian god lord king queen prince princess major royal justice legend
    austin dallas houston denver phoenix boston seattle chicago atlanta nashville memphis orlando
    paris london sydney brooklyn cairo berlin vienna geneva milan florida texas arizona nevada
    montana dakota georgia virginia carolina tennessee kentucky india china asia africa america
    kenya israel egypt
    """.split()
)


def main():
    with tempfile.NamedTemporaryFile(suffix=".rda") as download:
        with urllib.request.urlopen(SOURCE, timeout=120) as response:
            download.write(response.read())
        download.flush()
        frame = rdata.conversion.convert(rdata.parser.parse_file(download.name))["babynames"]

    recent = frame[frame["year"] >= SINCE_YEAR]
    totals = recent.groupby(recent["name"].str.lower())["n"].sum()
    names = sorted(
        name
        for name, births in totals.items()
        if births >= MIN_BIRTHS and len(name) >= 3 and name.isalpha() and name not in EXCLUDED
    )

    lines = []
    line = ""
    for name in names:
        if len(line) + len(name) + 1 > 100:
            lines.append(line)
            line = ""
        line += (" " if line else "") + name
    lines.append(line)
    body = "\n".join(lines)

    OUTPUT.write_text(
        "// Generated by scripts/generate_first_names.py. Do not edit.\n"
        "// US Social Security Administration baby-name data (public domain), via the CC0 babynames\n"
        f"// R package: names given to at least {MIN_BIRTHS} babies since {SINCE_YEAR}.\n\n"
        "enum FirstNames {\n"
        f"    static let count = {len(names)}\n\n"
        '    static let all: Set<Substring> = Set(list.split(whereSeparator: \\.isWhitespace))\n\n'
        '    private static let list = """\n'
        f"{body}\n"
        '"""\n'
        "}\n"
    )
    print(f"wrote {len(names)} names to {OUTPUT.relative_to(OUTPUT.parents[3])}")


if __name__ == "__main__":
    main()
