#!/usr/bin/env python3
"""Download the Core ML models mini-meeting-minutes needs and vendor them into Models/.

This is a maintainer tool. Users never run it: its output is committed, so a plain
`git clone` carries every model the app uses.

GitHub rejects files over 100 MiB and warns above 50 MiB, so any file larger than
PART_SIZE is split into numbered `.part-NNN` files. The app reassembles and SHA-256
verifies them on first run (see ModelStore.swift); the reassembled files are
gitignored.

Usage: python3 scripts/vendor_models.py
Standard library only; Python 3.9+.
"""

import hashlib
import json
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MODELS_DIR = ROOT / "Models"
MANIFEST = MODELS_DIR / "manifest.json"
GITIGNORE = ROOT / ".gitignore"
PART_SIZE = 45 * 1024 * 1024  # below GitHub's 50 MiB warning threshold

SOURCES = [
    {
        "name": "parakeet-redux",
        "purpose": "speech-to-text (Parakeet TDT 0.6B v3, ternary 'Redux' retrain)",
        "repo": "FluidInference/parakeet-redux-coreml",
        "revision": "8c5ef97a29cd120dc76b354b3f22b7fec3b486f9",
        "license": "CC-BY-4.0",
        "include": [
            "Preprocessor.mlmodelc",
            "Encoder.mlmodelc",
            "Decoder.mlmodelc",
            "JointDecisionv3.mlmodelc",
            "parakeet_vocab.json",
        ],
    },
    {
        "name": "speaker-diarization",
        "purpose": "speaker diarization (pyannote community-1 segmentation, WeSpeaker embeddings, PLDA)",
        "repo": "FluidInference/speaker-diarization-coreml",
        # The revision FluidAudio pins for its offline diarizer.
        "revision": "df2625ac79a7ac6b65ad868fee6d80f320da4232",
        "license": "CC-BY-4.0 (pyannote community-1, WeSpeaker, BUT Speech@FIT PLDA)",
        "include": [
            "Segmentation.mlmodelc",
            "FBank.mlmodelc",
            "Embedding.mlmodelc",
            "PldaRho.mlmodelc",
            "plda-parameters.json",
        ],
    },
    {
        "name": "silero-vad",
        "purpose": "voice activity detection (Silero VAD v6.2.1)",
        "repo": "FluidInference/silero-vad-coreml",
        "revision": "b419383c55c110e2c9271fa6ee0ea83d03c70d96",
        "license": "MIT",
        "include": ["silero-vad-unified-256ms-v6.2.1.mlmodelc"],
    },
    {
        "name": "localvqe",
        "purpose": "acoustic echo cancellation + noise suppression (LocalVQE v1.3, 4.8M params)",
        "repo": "FluidInference/localvqe-coreml",
        "revision": "4205430781c240397073d6f7bf676fb4c732fc12",
        "license": "Apache-2.0",
        "include": ["localvqe-v1.3-4.8M-256ms.mlmodelc"],
    },
]

GITIGNORE_BEGIN = "# BEGIN reassembled model files (generated by scripts/vendor_models.py)"
GITIGNORE_END = "# END reassembled model files"


def fetch_json(url):
    with urllib.request.urlopen(url, timeout=60) as response:
        return json.load(response)


def sha256_of(path):
    digest = hashlib.sha256()
    with open(path, "rb") as handle:
        for block in iter(lambda: handle.read(1 << 20), b""):
            digest.update(block)
    return digest.hexdigest()


def remote_files(source):
    url = f"https://huggingface.co/api/models/{source['repo']}/tree/{source['revision']}?recursive=true"
    items = fetch_json(url)
    wanted = source["include"]
    files = [
        item
        for item in items
        if item["type"] == "file"
        and any(item["path"] == w or item["path"].startswith(w + "/") for w in wanted)
    ]
    missing = [w for w in wanted if not any(f["path"] == w or f["path"].startswith(w + "/") for f in files)]
    if missing:
        sys.exit(f"{source['repo']}@{source['revision']} is missing {missing}")
    return files


def download(source, item, destination):
    url = f"https://huggingface.co/{source['repo']}/resolve/{source['revision']}/{item['path']}"
    destination.parent.mkdir(parents=True, exist_ok=True)
    temporary = destination.with_name(destination.name + ".download")
    with urllib.request.urlopen(url, timeout=120) as response, open(temporary, "wb") as out:
        while True:
            block = response.read(1 << 20)
            if not block:
                break
            out.write(block)
    if temporary.stat().st_size != item["size"]:
        sys.exit(f"size mismatch for {item['path']}: got {temporary.stat().st_size}, want {item['size']}")
    temporary.replace(destination)


def split(path):
    parts = []
    with open(path, "rb") as handle:
        index = 0
        while True:
            block = handle.read(PART_SIZE)
            if not block:
                break
            part = path.with_name(f"{path.name}.part-{index:03d}")
            part.write_bytes(block)
            parts.append(part)
            index += 1
    path.unlink()
    return parts


def update_gitignore(reassembled):
    lines = GITIGNORE.read_text().splitlines() if GITIGNORE.exists() else []
    if GITIGNORE_BEGIN in lines:
        start = lines.index(GITIGNORE_BEGIN)
        end = lines.index(GITIGNORE_END)
        del lines[start : end + 1]
    while lines and lines[-1] == "":
        lines.pop()
    block = [GITIGNORE_BEGIN] + [f"/Models/{path}" for path in sorted(reassembled)] + [GITIGNORE_END]
    GITIGNORE.write_text("\n".join(lines + [""] + block) + "\n")


def main():
    manifest_files = []
    reassembled = []
    for source in SOURCES:
        print(f"{source['repo']} @ {source['revision'][:12]}")
        for item in remote_files(source):
            relative = f"{source['name']}/{item['path']}"
            destination = MODELS_DIR / relative
            expected_sha = (item.get("lfs") or {}).get("oid")

            parts = sorted(destination.parent.glob(destination.name + ".part-*"))
            if parts:
                digest = hashlib.sha256()
                for part in parts:
                    digest.update(part.read_bytes())
                have_sha = digest.hexdigest()
            elif destination.exists():
                have_sha = sha256_of(destination)
            else:
                have_sha = None

            if have_sha is None or (expected_sha and have_sha != expected_sha):
                print(f"  downloading {item['path']} ({item['size'] / 1e6:.1f} MB)")
                for stale in parts:
                    stale.unlink()
                download(source, item, destination)
                have_sha = sha256_of(destination)
                if expected_sha and have_sha != expected_sha:
                    sys.exit(f"sha256 mismatch for {item['path']}")
                parts = []

            entry = {"path": relative, "size": item["size"], "sha256": have_sha}
            if item["size"] > PART_SIZE:
                if not parts:
                    parts = split(destination)
                entry["parts"] = [str(p.relative_to(MODELS_DIR)) for p in parts]
                reassembled.append(relative)
            manifest_files.append(entry)

    manifest = {
        "formatVersion": 1,
        "partSize": PART_SIZE,
        "sources": [{k: v for k, v in s.items() if k != "include"} | {"files": s["include"]} for s in SOURCES],
        "files": sorted(manifest_files, key=lambda f: f["path"]),
    }
    MANIFEST.write_text(json.dumps(manifest, indent=2) + "\n")
    update_gitignore(reassembled)
    total = sum(f["size"] for f in manifest_files)
    print(f"vendored {len(manifest_files)} files, {total / 1e6:.1f} MB; {len(reassembled)} split for GitHub")


if __name__ == "__main__":
    main()
